sudo: false
language: php
notifications:
  email:
    on_success: never
    on_failure: change
env:
  global:
  - GIT_COMMITTER_NAME=mirucon
  - GIT_COMMITTER_EMAIL=i@miruc.co
  - GIT_AUTHOR_NAME=mirucon
  - GIT_AUTHOR_EMAIL=i@miruc.co
  - secure: F4XGOaZtOyrOeOSMbVO8JjtLnIxIa/ywbHZDPNaJ1RPgVZ15OjeSHbR5jFem02eiOreTSyZwTrYWwJnUskA9djPEa2yfjBAxNj+JnPJ/h4tDG8FNgbXjwdDL15xl2aNKhi3QEdNe1TwopAJEh0JTRsGBp3laBykqE7jHPfknxkWpA5cy8qMccYq4aIjDq/UJxW3a3e8PSF2b8PTYlWmZgSaGmFt5Np/F1fULBYuJk/e4eD+8FzG9/y9EImfHt3SIxvCHBdEZrF5FoeP+gVfhEV6zh7G33GvBlWyBMfTuEEYMNC6BD7qLxpb2XQgHHIRUGGoSSFRh5G63uQg2nuI7toTF9qaOjWZRMSfeCqICzsiIVR2w1OqARuFXM6Qi7HXYD0yjzEXlTgm1KuNFLlmD+90yBnkH+oXVLtFgFA8ENXnru/+xfGiX/0jtdn+XfM7jUsbrZjUdygpEnLN1Cra0GxKBTkK990MXim1aCS4PiGsMq5CMKxVVR9eNQqVQBOeFerF9wB7yvhzb0w/yKnswVuN9W4B6j87RwgH1ScMrZp5IoWGVqCTi7clzqv9QRJheeB2Z1WymxWlS87p8moeB3V2wWC02xL2Q0HTJu2Aku3kxQseLvPQ4zMWlNSP+TO+8d65b+iovPnil6yS7Ow5VUU9QVDA8RxStgNrnbbxo4jo=
branches:
  only:
  - master
cache:
  directories:
  - vendor
  - "$HOME/.composer/cache"
matrix:
  include:
  - php: 7.2
    env: WP_VERSION=trunk
  - php: 7.2
    env: WP_VERSION=latest
  - php: 7.1
    env: WP_VERSION=latest
  - php: 7.0
    env: WP_VERSION=latest
  - php: 5.6
    env: WP_VERSION=4.4
  - php: 5.6
    env: WP_VERSION=latest
  - php: 5.6
    env: WP_VERSION=trunk
  - php: 5.6
    env: WP_TRAVISCI=phpcs
  - php: 5.3
    env: WP_VERSION=latest
    dist: precise
before_script:
- export PATH="$HOME/.composer/vendor/bin:$PATH"
- composer global require wp-coding-standards/wpcs
- |
    if [[ ${TRAVIS_PHP_VERSION} == "7.2" ]]; then
      composer install
    fi
- nvm install 8
- npm install
- |
  if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
    phpenv config-rm xdebug.ini
  else
    echo "xdebug.ini does not exist"
  fi
- |
  if [[ ! -z "$WP_VERSION" ]] ; then
    bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    wp theme install coldbox --activate --force --quiet
    if [[ ${TRAVIS_PHP_VERSION:0:2} == "5." ]]; then
      composer global require "phpunit/phpunit=4.8.*"
    else
      composer global require "phpunit/phpunit=5.7.*"
    fi
  fi
- |
  if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
    composer global require wp-coding-standards/wpcs
    phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs
  fi
script:
- |
  if [[ ! -z "$WP_VERSION" ]] ; then
    phpunit
    WP_MULTISITE=1 phpunit
  fi
- |
  if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
    phpcs
  fi
after_success:
- bash ./bin/deploy.sh
